### ISSUE TITLE
Awesome-List-RootKits

### ISSUE THREAD

**Issue by ArkinGreek** [d30sa1/RootKits-List-Download#9]
https://github.com/milabs/awesome-linux-rootkits

**Comment by loneicewolf** [comment]
@ArkinGreek  Yes! totally agree on this one brilliant contribution! 🥇

**Comment by d30sa1** [comment]
Sure thing.

**Comment by loneicewolf** [comment]
I think this issue can be solved/resolved/closed; 
thanks @ArkinGreek  for suggesting it; 
## have a great day on both of you people! :)
